[Server]
hostname = localhost
port = 8080
https = false

[Cache]
redisHost = nitter-redis
redisPort = 6379
redisConnections = 20
redisMaxConnections = 30

[Config]
hmacKey = CHANGE_ME_TO_A_LONG_RANDOM_SECRET